spring:
  config:
    activate:
      on-profile: auth

  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(0/jpGUSpyXXyUUSg7VUt43bNver51DSJdcSdaYzQLGzngOjYQH9gdTzK5kjS7Pee)
            client-secret: ENC(vdxKrgpB5MYlI7LN9aFB/8DRKbzzXQQgZ1uPwxi/OYAAM1VX1NKcFydb55aunclB)
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post
            client-name: Kakao

          naver:
            authorization-grant-type: authorization_code
            client-id: ENC(7Qx1ww0AAtGR5/BEwzOPaGEu9SZQF/XULQeR6EVM5ik=)
            client-secret: ENC(muOgDi4oKweWUnGtKfuZE2hE4R7WA4kE)
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-authentication-method: client_secret_post
            client-name: Naver

          google:
            authorization-grant-type: authorization_code
            client-id: ENC(MM7iKbafVgZdHDZVJwQJF/hZssrb6lbWOf0OCvVjDaYz2Y2xryxnAlt4EN0f8oCwqjd9MzRgEklm2d1xTBdHJ2A8pU92WMKkDJ+EogUozJVpWkX4E8YuQQ==)
            client-secret: ENC(CwacoQtrMof6YFd+KJnjtbIVSXdbFszbOjhGHxKEi9OVovRvhYKGtNrhGS51Z1KI)
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - email
            client-authentication-method: client_secret_post
            client-name: Google

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub