apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailfriends-back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tailfriends-back
  template:
    metadata:
      labels:
        app: tailfriends-back
    spec:
      containers:
        - name: tailfriends-back
          image: s9kpv31a.kr.private-ncr.ntruss.com/tailfriends/tailfriends-back:__TAG__
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tailfriends-back-service
spec:
  selector:
    app: tailfriends-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
