spring:
  profiles:
    active: local, auth

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonDeserializer
    consumer:
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: chat-room

  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(Fi1nTnA6Fv9u/6yzXpkQ6OgkGroVPEFrAkimx5mh9cM=)
    password: ENC(IzfpKLfwDbkCCIoV5jaG1nfZlefguY4x)
    properties:
      mail:
        smtp:
          auth: true
          starttls: false
          ssl: true
          timeout: "5000"
          connectiontimeout: "5000"
          writetimeout: 5000
    default-encoding: UTF-8
    auth-code-expiration-millis: 300000

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${JASYPT_KEY}

server:
  servlet:
    session:
      timeout: 180m
      cookie:
        same-site: none
        secure: true

cloud:
  ncp:
    storage:
      endpoint: https://kr.object.ncloudstorage.com
      region: kr-standard
      access-key: ENC(m/bNDe7GWD/6JyfXzjNL08L2c9a3oEpuDGL4FAeTqu1GmDrYIhH/YA==)
      secret-key: ENC(lYv+w5ipmXiiaZ/9bp3OeqO2RoArVCalbyA/22qZCpYhZlZMexJ1OT8TJGOySfgCNUeNg90Z7UI=)
      bucket: yog-img-storage-gw

kakao:
  api:
    scriptKey: ENC(rx4OdzFCwme5wNInUfdwd6gB9yQKjrUPUQQjYvoYckQQienCjDrV8NPhqKnoPHNA)

app:
  name: © 2025 요기오디짐
  version: v1.3.0